title: Regex Extractor
description: >-
  Given a regular expression as input, this Add-On searches through each document for matches. You can chose to add "tags" or "key-value" pairs to your document so that document is marked with the first instance of the match that is found.
  This Add-On also outputs a CSV that lists all matches found in a given document and the page number the match was was found on. This can be helpful for analysis or inspecting your results
instructions: ''
type: object
documents:
  - selected
  - query
properties:
  regex:
    title: Regex
    type: string
    description: The regular expression that you would like to search your documents for. 
  annotate:
    title: Annotate
    type: boolean
    description: Annotate pages where regex matches are found. 
    default: false
  annotation_access:
    title: Access Level
    type: string
    description: Access level for posted annotations with matches.
    enum:
      - private
      - organization
      - public
    default: private
  key:
    title: Key
    type: string
    description: Use a key-value pair, where your regex match is the value and you set the key. Keep _tag if you want the regular expression match to appear as a standalone "tag" and not a key-value pair. 
    default: _tag
required: [regex]
categories: 
  - extraction 
