title: Regex Extractor
description: >-
  This will return a JSON file of all strings the given regex matches in
  the selected files
type: object
documents:
  - selected
properties:
  regex:
    title: Regex
    type: string
    format: regex
  annotate:
    title: Annotate
    type: boolean
    default: false
required: [regex]
