title: Regex Extractor
description: >-
  Given a regular expression as input, this Add-On searches through each document for matches.
  It outputs a CSV listing the regular expression, the match, the document it was found in,
  and the page number the match was was found on. 
type: object
documents:
  - selected
properties:
  regex:
    title: Regex
    type: string
    format: regex
required: [regex]
categories: 
  - extraction 
