title: Regex Extractor
description: >-
  Given a regular expression as input, this Add-On searches through each document for matches.
  It outputs a CSV listing the regular expression, the match, the document it was found in,
  and the page number the match was was found on. 
instructions: ''
type: object
documents:
  - selected
  - query
properties:
  regex:
    title: Regex
    type: string
  annotate:
    title: Annotate
    type: boolean
    description: Annotate pages where regex matches are found. 
    default: false
  annotation_access:
    title: Access Level
    type: string
    description: Access level for posted annotations with matches.
    enum:
      - private
      - organization
      - public
    default: private
  tag_name:
    title: Tag
    type: string
required: [regex]
categories: 
  - extraction 
